POST http://127.0.0.1:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVhc3lVc2VyTmFtZSIsImlkIjoiNmE5ZTRlZGRhNjUzZWJiM2MwNWRiYTNmIiwiaWF0IjoxNzg4NzY0MzI2fQ.TJ-ldkq8p2S5KeSvhhtNJbtgVNhs9--iglE5Fw7qdIA

{
"content": "Single page apps use token based auth.",
"important": false
}